### ISSUE TITLE
 (IMPORT FAILED): G:\comfyui_video\custom_nodes\comfyui_musev_evolved

### ISSUE THREAD

**Issue by 108863258** [storyicon/comfyui_musev_evolved#9]
(IMPORT FAILED): G:\comfyui_video\custom_nodes\comfyui_musev_evolved

**Comment by shadowyli** [comment]
> (IMPORT FAILED): G:\comfyui_video\custom_nodes\comfyui_musev_evolved

Same. Did you solve it?

**Comment by aurel-g** [comment]
Same here,

```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/nodes.py", line 1, in <module>
    from .v1 import MuseVPredictorV1, MuseVImg2VidV1
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/v1.py", line 22, in <module>
    from .MMCM.mmcm.utils.seed_util import set_all_seed
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/MMCM/mmcm/__init__.py", line 3, in <module>
    from .music import *
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/MMCM/mmcm/music/__init__.py", line 1, in <module>
    from .music_map.music_map import MusicMap, MusicMapSeq
  File "/mnt/comfyui/app/custom_nodes/comfyui_musev_evolved/MMCM/mmcm/music/music_map/music_map.py", line 4, in <module>
    from moviepy.editor import concatenate_audioclips, AudioClip, AudioFileClip
ModuleNotFoundError: No module named 'moviepy.editor'

Cannot import /mnt/comfyui/app/custom_nodes/comfyui_musev_evolved module for custom nodes: No module named 'moviepy.editor'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.3 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/comfyui_musev_evolved

Starting server

To see the GUI go to: http://0.0.0.0:8080
```

Though moviepy is installed in my venv

**Comment by aurel-g** [comment]
Try with `moviepy==1.0.3`
